import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Search from '@/components/Search'
import Navbar from '@/components/Navbar'
import GridViewCard from '@/components/GridViewCard'
import Link from 'next/link'
import ListViewCard from '@/components/ListViewCard'
import { useState } from 'react'
import { IoGridOutline, IoListOutline } from 'react-icons/io5'
import Card from '@/components/Card'
import { jobs } from '@/data/jobs'
const inter = Inter({ subsets: ['latin'] })
const jobData = [
  {
    title: 'web dev',
    location: 'India',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    time: 'now',
    type: 'full-time',
    skills: ['react', 'node', 'js'],
    link: '/work/web-dev-03039i19943'
  },
  {
    title: 'python dev',
    location: 'combodia',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    time: 'now',
    type: 'contract',
    skills: ['python', 'node', 'js'],
    link: '/work/python-dev-03039i19943'
  },
  {
    title: 'web dev',
    location: 'India',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    time: 'now',
    type: 'full-time',
    skills: ['react', 'node', 'js'],
    link: '/work/web-dev-dedededed'
  },
  {
    title: 'laravel dev',
    location: 'france',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    time: 'now',
    type: 'contract',
    skills: ['laravel', 'livewire', 'vuejs'],
    link: '/work/laravel-dev-03039i19943'
  },
  {
    title: 'cpp dev',
    location: 'India',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    time: 'now',
    type: 'full-time',
    skills: ['cpp', 'c', 'js'],
    link: '/work/cpp-dev-03039i19943'
  },
  {
    title: 'vue js',
    location: 'India',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.',
    time: 'now',
    type: 'full-time',
    skills: ['vuejs', 'node', 'js'],
    link: '/work/vuejs-dev-03039i19943'
  }

]
export default function Home() {
  const [viewAs, setViewAs] = useState('list')
  console.log(jobs)
  return (
    <>
      <Head>
        <title>Job Hive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='md:w-[85%] m-auto 
      '>
        <Navbar />
        <Search />

        <div className='mt-10 flex justify-end
        '>

          <button
            title='View as list'
            onClick={() => setViewAs('list')} className=' mr-2'><IoListOutline
              className={` text-4xl
              ${viewAs === 'list' ? 'text-blue-500' : 'text-gray-500'}
              `}
            /></button>
          <button
            title='View as grid'
            onClick={() => setViewAs('grid')} className=''><IoGridOutline
              className={` text-3xl
              ${viewAs === 'grid' ? 'text-blue-500' : 'text-gray-500'}
            `}
            />
          </button>
        </div>
        <h1 className='text-2xl font-bold text-gray-800 mt-10 mb-5'>Recent Jobs</h1>
        {
          viewAs === 'list' ? (

            <div>
              <div className="job-card-container
        ">
                {jobData.map((job, i) => (
                  <div key={i}>
                    <Link
                      href={job.link}
                    >
                      <ListViewCard
                        title={job.title}
                        location={job.location}
                        description={job.description}
                        time={job.time}
                        type={job.type}
                        skills={job.skills}
                      />
                    </Link>
                  </div>
                ))}
              </div>

            </div>
          ) : (

              <div className='mx-6 mb-8 mt-14 grid max-w-[1190px] grid-cols-1 gap-y-12 sm:mx-auto sm:mb-14 sm:mt-[70px] sm:grid-cols-2 
            sm:gap-x-3 sm:gap-y-16 sm:px-10 lg:mt-[105px] lg:grid-cols-3 lg:gap-x-[30px] 
            '>
              {
                jobs.map((job, i) => (
                  <div key={i}>
                    <GridViewCard
                      id={job.id}
                      company={job.company}
                      logo={job.logo}
                      logoBackground={job.logoBackground}
                      position={job.position}
                      postedAt={job.postedAt}
                      contract={job.contract}
                      location={job.location}
                    />
                  </div>
                ))

              }
            </div>
          )
        }

      </main>
    </>
  )
}
